# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My blog
email: info@fhergomez.com
description: > # this means to ignore newlines until "baseurl:"
  Here I will be describing my journey of coding for the next 100 days of code. You're welcome to follow me, and as I progress, hopefully I'll be able to figure out how to add comments to this blog. For the meantime, you can email me if you have any suggestions or ideas on how I can add comments to this blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fernandogomez.io" # the base hostname & protocol for your site
twitter_username: fhergomez70
github_username:  fhergomez

# Build settings
markdown: kramdown
